### ISSUE TITLE
StatusCodeError: 500 Framework tensorflow and version 1.12-py36 is not supported on gpu trainings

### ISSUE THREAD

**Issue by jufabeck2202** [cloud-annotations/training#101]
After updating to the latest version I´m now getting the following error when I start the training:
```
⠹ Starting training run...(node:1192) UnhandledPromiseRejectionWarning: StatusCodeError: 500 - {"trace":"_","errors":[{"code":"training_submit_error","message":"INVALID_ARGUMENT: Framework tensorflow and version 1.12-py36 is not supported on gpu trainings","more_info":"http://watson-ml-api.mybluemix.net/"}]}
    at new StatusCodeError (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1083:12)
(node:1192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I tried training on the London and Dallas Location and got the error on both

**Comment by sachinshelke** [comment]
I'm also facing the same issue after updating cli version to 1.1.5
here is the config
gpu : v100x2
steps: 200000

error details
```
(tensorflow) IBMCustomTraining$ cacli train trainer.zip 
(Using settings from config.yaml)
⠹ Starting training run...(node:4481) UnhandledPromiseRejectionWarning: StatusCodeError: 500 - {"trace":"_","errors":[{"code":"training_submit_error","message":"INVALID_ARGUMENT: Framework tensorflow and version 1.12-py36 is not supported on gpu trainings","more_info":"http://watson-ml-api.mybluemix.net/"}]}
    at new StatusCodeError (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1083:12)
(node:4481) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4481) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I tried with custom zip and default train option as well. But error on both side.

**Comment by bourdakos1** [comment]
😭

**Comment by bourdakos1** [comment]
I will fix this, I’m so sorry for all the problems

**Comment by bourdakos1** [comment]
try v1.1.6

**Comment by jufabeck2202** [comment]
awesome! worked for me

**Comment by sachinshelke** [comment]
It's working. Wow. Thanks @bourdakos1

**Comment by sachinshelke** [comment]
Just a quick query
Can it be possible see the eval report while training progress? (tensorboard progress status)
