### ISSUE TITLE
cacli train:UnhandledPromiseRejectionWarning: RequestError: Error: connect ETIMEDOUT 169.61.47.130:80

### ISSUE THREAD

**Issue by Vejay-Karthy** [cloud-annotations/training#115]
Hey! I want to create a object detection model using ibm cloud. I am following this tutorial : https://cloud-annotations.github.io/training/object-detection/cli/index.html
 When I train the model,that is, when I gave "cacli train" i got the following error:
⠸ Starting training run...(node:16964) UnhandledPromiseRejectionWarning: RequestError: Error: connect ETIMEDOUT 169.61.47.130:80
    at new RequestError (C:\Users\sveja\AppData\Roaming\npm\node_modules\cloud-annotations\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\sveja\AppData\Roaming\npm\node_modules\cloud-annotations\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\sveja\AppData\Roaming\npm\node_modules\cloud-annotations\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\sveja\AppData\Roaming\npm\node_modules\cloud-annotations\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.onRequestError (C:\Users\sveja\AppData\Roaming\npm\node_modules\cloud-annotations\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at Socket.socketErrorListener (_http_client.js:392:9)
(node:16964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧ Starting training run...

My credentials are correct else there would have been an error staying Invalid Credentials.

My config.yaml file:
name: <some_name1>
buckets:
  training: <some_name2>
  output: <some_name3>
trainingParams:
  gpu: k80
  steps: '500'

I also get this same error when i run "cacli list".
Can anyone explain me why am I getting this error and how do I rectify it?
Thanks in Advance!

**Comment by bourdakos1** [comment]
It's strange that `cacli list` doesn't work, what region are you using?

**Comment by Vejay-Karthy** [comment]
All my resources are in Dallas. 
In Cloud annotations, it is in "us".

**Comment by sachinshelke** [comment]
For me `cacli list` is working fine but `cacli train` gives an error below


**trainingParams:**
  gpu: v100x2
  steps: '200000'


```
TrainedModel$ cacli train
(Using settings from config.yaml)
⠏ Starting training run...(node:97513) UnhandledPromiseRejectionWarning: StatusCodeError: 500 - {"trace":"_","errors":[{"code":"training_submit_error","message":"RESOURCE_EXHAUSTED: job could not be queued, queue size exceeds limit","more_info":"http://watson-ml-api.mybluemix.net/"}]}
    at new StatusCodeError (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1083:12)
(node:97513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:97513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠼ Starting training run...

```

Is this Specific error says something (I didn't found anything related on IBM portal)

```
{
  "trace": "_",
  "errors": [
    {
      "code": "training_submit_error",
      "message": "RESOURCE_EXHAUSTED: job could not be queued, queue size exceeds limit",
      "more_info": "http://watson-ml-api.mybluemix.net/"
    }
  ]
}
```

**Comment by bourdakos1** [comment]
@sachinshelke `RESOURCE_EXHAUSTED` just means there are no GPUs and the queue is so long you can't be added to it, just try again later and cross your fingers 😬

@Vejay-Karthy `ETIMEDOUT` normally means the network call took too long, do you have **really** slow internet?

**Comment by sachinshelke** [comment]
@bourdakos1 Thanks for reply.
I'm getting `RESOURCE_EXHAUSTED` error only when using `cacli version 1.1.8`.
But when I downgrade cacli version to `1.1.6`, training status is in `pending` since last 3 hrs. whereas in 1.1.8 it shows status as `error`.

Is it something like, same error got in V.1.1.6 but not handled and in v1.1.8 it is handled?

**Comment by bourdakos1** [comment]
@sachinshelke The `RESOURCE_EXHAUSTED` error isn't dependent on the version of cacli. It was just by chance you were able to make it into the queue after downgrading to `cacli version 1.1.6`
