### ISSUE TITLE
failed to run cacli list and cacli train

### ISSUE THREAD

**Issue by liusicun** [cloud-annotations/training#116]
for cacli list i get:

(node:20857) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /v2/endpoints/v3/models</pre>\n</body>\n</html>\n"
    at new StatusCodeError (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:185:22)
    at Request.emit (events.js:209:13)
    at Request.EventEmitter.emit (domain.js:476:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:209:13)
    at Request.EventEmitter.emit (domain.js:476:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1083:12)
(node:20857) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20857) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

for cacli train i get errors like this :

⠹ Starting training run...(node:20880) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /v2/endpoints/v3/ml_assets/training_definitions</pre>\n</body>\n</html>\n"
    at new StatusCodeError (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:185:22)
    at Request.emit (events.js:209:13)
    at Request.EventEmitter.emit (domain.js:476:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:209:13)
    at Request.EventEmitter.emit (domain.js:476:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1083:12)
(node:20880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

how to solve those problems? thank you very much!

**Comment by bourdakos1** [comment]
This may be related to issue #115

**Comment by liusicun** [comment]
@bourdakos1  
today i started over and run the cacli list
i get this error:

⠼ Starting training run...(node:22533) UnhandledPromiseRejectionWarning: RequestError: Error: socket hang up
    at new RequestError (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:185:22)
    at Request.emit (events.js:214:15)
    at Request.EventEmitter.emit (domain.js:476:20)
    at Request.onRequestError (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:209:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at TLSSocket.socketOnEnd (_http_client.js:440:9)
(node:22533) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22533) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


this shows :"socket hang up"  
it wasn't show up yesterday.

thank you.

**Comment by liusicun** [comment]
@bourdakos1 when i run cacli list, it works, but nothing there. 
<img width="597" alt="屏幕快照 2019-09-07 11 37 04" src="https://user-images.githubusercontent.com/36632692/64469408-d9598180-d163-11e9-9951-fbc4194f872e.png">

**Comment by liusicun** [comment]
@bourdakos1  so i tried again this afternoon. the cacli train works fine.
after train completed i tried to run ` cacli download <model_id>` to download but here comes new error ::


(node:25701) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - {"trace":"6e9bffca2ac093df5a77454154cc4f63","errors":[{"code":"cannot_find_job_status","message":"Training job status cannot be obtained.","more_info":"http://watson-ml-api.mybluemix.net/"}]}
    at new StatusCodeError (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:185:22)
    at Request.emit (events.js:209:13)
    at Request.EventEmitter.emit (domain.js:476:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:209:13)
    at Request.EventEmitter.emit (domain.js:476:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1083:12)
(node:25701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 thank you.

**Comment by bourdakos1** [comment]
I think your connection or Watson machine learning might be flaky? Just keep trying I guess? What region are you using and where do you live and how fast is your internet?

**Comment by bourdakos1** [comment]
The further you live from Dallas, the further the data needs to travel

**Comment by liusicun** [comment]
@bourdakos1 
Watson machine learning is in Dallas, and Cloud Object Storage is in us.
I am living in China, but I use VPS(located in us also) via shadowsocks when it's necessary. 
tried both with and without VPS but doesn't work. 

i will keep trying.

**Comment by liusicun** [comment]
@bourdakos1  I get 6mbp per second for download speed, I don't know if it's fast enough.
