### ISSUE TITLE
cacli train: Starting training run...(node:5088) UnhandledPromiseRejectionWarning: RequestError: Error: connect ETIMEDOUT 192.30.252.131:443

### ISSUE THREAD

**Issue by YOUYOUNG** [cloud-annotations/training#130]
(Using settings from config.yaml)
⠼ Starting training run...(node:5088) UnhandledPromiseRejectionWarning: RequestError: Error: connect ETIMEDOUT 192.30.252.131:443
    at new RequestError (F:\软件\node\node_global\node_modules\cloud-annotations\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (F:\软件\node\node_global\node_modules\cloud-annotations\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (F:\软件\node\node_global\node_modules\cloud-annotations\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (F:\软件\node\node_global\node_modules\cloud-annotations\node_modules\request\request.js:185:22)
    at Request.emit (events.js:205:15)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.onRequestError (F:\软件\node\node_global\node_modules\cloud-annotations\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:200:13)
    at ClientRequest.EventEmitter.emit (domain.js:471:20)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
(node:5088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
(rejection id: 1)
(node:5088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠼ Starting training run...

my resoures and init
resource：Dallas， region: us

**Comment by YOUYOUNG** [comment]
![image](https://user-images.githubusercontent.com/15604461/66732880-38f82a80-ee90-11e9-815f-5c7bf8a7fde1.png)

**Comment by bourdakos1** [comment]
I think the request is just timing out, not sure if there's anything I can do about it 🙁
