### ISSUE TITLE
Error running cacli train 

### ISSUE THREAD

**Issue by sagarp2901** [cloud-annotations/training#59]
Getting the following error while trying to run this command 
**cacli train** after running **npm install -g cloud-annotations** as per this tutorial: https://cloud-annotations.github.io/training/classification/cli/7.html

Error:
C:\Users\xydy\AppData\Roaming\npm\node_modules\cloud-annotations\src\commands\init.js:52
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\xydy\AppData\Roaming\npm\node_modules\cloud-annotations\src\index.js:3:14)

**Comment by bourdakos1** [comment]
I think cacli has a dependency on node version v10, try installing 10+

**Comment by sagarp2901** [comment]
Okay. I will try upgrading my node. Thanks!

Sagar

**Comment by sagarp2901** [comment]
I am past that now after upgrading my node but now I am seeing this issue:

cacli train
(Using settings from config.yaml)
⠦ Starting training run...(node:5864) UnhandledPromiseRejectionWarning: StatusCodeError: 400 - {"trace":"448714abb2feffaa99bb0689777c406e","errors":[{"code":"invalid_parameter_name","message":"Invalid value:  for field: bucket","more_info":"http://watson-ml-api.mybluemix.net/"}]}
    at new StatusCodeError (C:\Users\Sagar Jinal\AppData\Roaming\npm\node_modules\cloud-annotations\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\Sagar Jinal\AppData\Roaming\npm\node_modules\cloud-annotations\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\Sagar Jinal\AppData\Roaming\npm\node_modules\cloud-annotations\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\Sagar Jinal\AppData\Roaming\npm\node_modules\cloud-annotations\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (C:\Users\Sagar Jinal\AppData\Roaming\npm\node_modules\cloud-annotations\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (C:\Users\Sagar Jinal\AppData\Roaming\npm\node_modules\cloud-annotations\node_modules\request\request.js:1083:12)
(node:5864) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5864) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧ Starting training run...

**Comment by bourdakos1** [comment]
Can you paste a copy of the config.yaml?

**Comment by sagarp2901** [comment]
name: untitled-project
credentials:
  wml:
    instance_id: 23d00ba6-f617-4e34-9108-bc72e6e95be7
    username: b16e076f-b001-455d-8c3d-3e5bfbe9d4a1
    password: 19c6a514-6dbf-47a3-8706-487be53afb56
    url: 'https://us-south.ml.cloud.ibm.com'
  cos:
    access_key_id: 92a1595b2b3341b2842df383a4103d31
    secret_access_key: f894ef6e7c438fca1d109b89c227d6b167617fbe2a5902cd
    region: us-south
buckets:
  training: ''
trainingParams: {}

**Comment by bourdakos1** [comment]
I think the problem is that you haven’t specified a training bucket. It’s just an empty string

**Comment by sagarp2901** [comment]
It didn't ask me before. But I re-created yaml and now here's my bucket:
buckets:
  training: linc4314
  output: linc4314

**Comment by sagarp2901** [comment]
Here's my new problem when trying to download the model:

C:\code>cacli train
(Using settings from config.yaml)
success Training run submitted.

Model ID:
┌────────────────┐
│ model-6ldx0ywd │
└────────────────┘

Would you like to monitor progress? (yes) yes

success Training in progress.
success Training complete.
success Model files saved to bucket.
✨ Done.

C:\code>cacli download model-6ldx0ywd
(Using settings from config.yaml)
Training was canceled or failed.

**Comment by bourdakos1** [comment]
How many images did you label?

**Comment by sagarp2901** [comment]
about 50 for each of the 3 categories.

**Comment by bourdakos1** [comment]
Did you drag rectangles on the objects?

**Comment by sagarp2901** [comment]
Sorry I don't get that question?
I did this step: https://cloud-annotations.github.io/training/classification/cli/5.html

**Comment by sagarp2901** [comment]
> Did you drag rectangles on the objects?

Yes, so I am trying out the object detection now and dragged rectangles around images.

**Comment by sagarp2901** [comment]
Object detection works for me now!
