### ISSUE TITLE
i got those problem...

### ISSUE THREAD

**Issue by Android-BRUCE** [cloud-annotations/training#69]
uest.plumbing.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.EventEmitter.emit (domain.js:481:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:197:13)
    at Request.EventEmitter.emit (domain.js:481:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1083:12)
(node:58734) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58734) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NikolinNgjela** [comment]
I have the same issue, sorry did you find a workaround for this one?

**Comment by Android-BRUCE** [comment]
> I have the same issue, sorry did you find a workaround for this one?

When I tried again with the teaching, I found it successful.but Training a Classification Model is always failed，Training an Object Detection Model successful

**Comment by bourdakos1** [comment]
@NikolinNgjela can you update cacli and try again? I fixed a bug with classification the other day
