### ISSUE TITLE
about Training a Classification Model always failed。

### ISSUE THREAD

**Issue by Android-BRUCE** [cloud-annotations/training#70]
i try Training a Classification Model 
and
Training an Object Detection Model 

but Training a Classification Model always failed。

---
error Training failed.
---

logs info
--
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 200
    at ClientRequest.req.on (/usr/local/lib/node_modules/cloud-annotations/node_modules/ws/lib/websocket.js:595:7)
    at ClientRequest.emit (events.js:197:13)
    at ClientRequest.EventEmitter.emit (domain.js:481:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:560:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
    at TLSSocket.socketOnData (_http_client.js:447:20)
    at TLSSocket.emit (events.js:197:13)
    at TLSSocket.EventEmitter.emit (domain.js:481:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
Emitted 'error' event at:
    at abortHandshake (/usr/local/lib/node_modules/cloud-annotations/node_modules/ws/lib/websocket.js:718:15)
    at ClientRequest.req.on (/usr/local/lib/node_modules/cloud-annotations/node_modules/ws/lib/websocket.js:595:7)
    [... lines matching original stack trace ...]
    at addChunk (_stream_readable.js:288:12)
--

**Comment by bourdakos1** [comment]
Try updating cacli
```
npm update -g cloud-annotations
```

**Comment by Android-BRUCE** [comment]
> Try updating cacli
> 
> ```
> npm update -g cloud-annotations
> ```

emmm，i try my best hahah,it does not work...

**Comment by bourdakos1** [comment]
did you get an error?

**Comment by Android-BRUCE** [comment]
> did you get an error?
thanks a lot !
I solved the problem
update tensorflow version 1.X to 2
`pip install tensorflow==2.0.0-alpha`
