### ISSUE TITLE
Starting training run...(node:27904) UnhandledPromiseRejectionWarning: StatusCodeError: 500

### ISSUE THREAD

**Issue by NikolinNgjela** [cloud-annotations/training#76]
When I execute the train command I'm having the following issue, 

Is this ok? (yes) yes

```
⠧ Starting training run...(node:27904) UnhandledPromiseRejectionWarning: StatusCodeError: 500 - {"trace":"cd36dd6c4ebd4b1c02d3a00d1499eec6","errors":[{"code":"training_submit_error","message":"UNAVAILABLE: io exception","more_info":"http://watson-ml-api.mybluemix.net/"}]}
    at new StatusCodeError (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\request-promise-core\lib\errors.js:32:15)

    at Request.RP$callback [as _callback] (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\request\request.js:185:22)

    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\request\request.js:1161:10)

    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\request\request.js:1083:12)
(node:27904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

also on my config.yaml 
I have only the following data 

```
buckets:
  training: nikolin-realtime-detect
name: nikolin-realtime-detect

```

**Comment by NikolinNgjela** [comment]
Running the cacli logs to my models I see the same error 

(node:13988) UnhandledPromiseRejectionWarning: NoSuchKey: The specified key does not exist.

delete the config.yaml and run the cacli init to interactively create a config.yaml file again.

```
buckets:
  training: nikolin-realtime-detect
trainingParams:
  gpu: k80
  steps: '500'
name: nikolin-realtime-detect
```
I've double check my credentials here in order to be sure that are correct 

Watson Machine Learning Credentials
instance_id: (b50463d2-zzzz-zzzz-zzzz-0bbd50f77bdb)
username: (fef4bbbe-zzzz-zzzz-zzzz-75ae1e0dbbbc)
password: (6510ac5d-zzzz-zzzz-zzzz-f83102d39fec)
url: (https://eu-de.ml.cloud.ibm.com)

Cloud Object Storage Credentials
access_key_id: (62c3zzzzzzzzzzzzzzzzzzzzf6021)
secret_access_key: (d98a4zzzzzzzzzzzzzzzzzzzzzzzz1166e447e)
region: (us-geo)

Buckets
training data bucket: nikolin-realtime-detect

and get the same log exception 

```
(node:14420) UnhandledPromiseRejectionWarning: NoSuchKey: The specified key does not exist.
    at Request.extractError (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\ibm-cos-sdk\lib\services\s3.js:601:35)
    at Request.callListeners (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\ibm-cos-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\ibm-cos-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\ibm-cos-sdk\lib\request.js:681:14)
    at Request.transition (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\ibm-cos-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\ibm-cos-sdk\lib\state_machine.js:14:12)
    at C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\ibm-cos-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\ibm-cos-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\ibm-cos-sdk\lib\request.js:683:12)
    at Request.callListeners (C:\Users\...\AppData\Roaming\nvm\v10.15.3\node_modules\cloud-annotations\node_modules\ibm-cos-sdk\lib\sequential_executor.js:115:18)
(node:14420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Qjizhi** [comment]
Hello, did you figure it out? I also met this error.

**Comment by NikolinNgjela** [comment]
> Hello, did you figure it out? I also met this error.

Not yet,

**Comment by bronxpaul** [comment]
Also facing the same issue. Not sure what's exactly causing it.

**Comment by bourdakos1** [comment]
I think a lot of people are having issues with the WML (https://eu-de.ml.cloud.ibm.com) region, I'm not sure why, but can someone try to create a WML instance in the us and see if that runs? I'll try the eu region and see if I'm met with similar errors

**Comment by bourdakos1** [comment]
Yea, I get the same error with the frankfurt region. I'll try to file an issue with the Watson team.

**Comment by bourdakos1** [comment]
Okay, the portion of WML that cacli uses is called DLaaS (Deep Learning as a Service) and it's only available in the London and Dallas regions. I'll update the documentation with this information

**Comment by NikolinNgjela** [comment]
@bourdakos1 , Yes thank you Nick, I was able to complete successfully the Training and download the model after I've changed the WML  region in London.

Also able to complete the tutorial and get the output :)) Thank you for sharing! 👍
