### ISSUE TITLE
cacli train error

### ISSUE THREAD

**Issue by fclyyxy1999** [cloud-annotations/training#88]
Hello, I want to train my own model, but no matter how I initialize and train, I always get the following error。

⠸ Starting training run...(node:16263) UnhandledPromiseRejectionWarning: StatusCodeError: 400 - {"trace":"72f5e00064b3541c494e135124fe05b7","errors":[{"code":"training_failed","message":"Manifest Error: The value of resource should be either k80, k80x2, k80x4, v100 or v100x2","more_info":"http://watson-ml-api.mybluemix.net/"}]}
    at new StatusCodeError (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cloud-annotations/node_modules/request/request.js:1083:12)
(node:16263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16263) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I have seen #76 ,and I have switched Machine Learning for all four zones.

Here is my init:

Watson Machine Learning Credentials
instance_id: (1f192482-aaaa-aaaa-aaaa-de777b0131d6) 
username: (122b54b8-aaaa-aaaa-aaaa-219c5e8ce6e2) 
password: (fa790bcd-aaaa-aaaa-aaaa-29dcc4cac596) 
url: (https://us-south.ml.cloud.ibm.com) 

Cloud Object Storage Credentials
access_key_id: (5157792aaaaaaaaaaaa7e14a2b4bef35a4) 
secret_access_key: (9ec97efd8aaaaaaaaaaaa8c43487d6aace61238e) 
region: (us-south)       (I change it according to the buckets)

Buckets
training data bucket: lxk
output bucket: lxk

Training Params
gpu: (1050Ti) 
steps: (100) 

project name: (lxk) 

Here is my config.yaml:
name: lxk
buckets:
  training: lxk
  output: lxk
trainingParams:
  gpu: 1050Ti
  steps: '100'

I don't know what I've done wrong, but I've trained in the same way before, and I've also re-installed cloud-annotations. I really can't think of a way.Please help me!! Thanks a lot!

**Comment by bourdakos1** [comment]
The issue is that you chose `1050Ti` as your GPU,  at the moment we only support `k80`, `k80x2`, `k80x4`, `v100` or `v100x2`
