### ISSUE TITLE
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'

### ISSUE THREAD

**Issue by atomsmasher81** [cloud-annotations/training#9]
after running this
`python -m object_detection.model_main \ --pipeline_config_path=.tmp/pipeline.config \ --model_dir=.tmp/checkpoint`
i am getting this error
`WARNING:tensorflow:Forced number of epochs for all eval validations to be 1.
WARNING:tensorflow:Expected number of evaluation epochs is 1, but instead encountered `eval_on_train_input_config.num_epochs` = 0. Overwriting `num_epochs` to 1.
WARNING:tensorflow:Estimator's model_fn (<function create_model_fn.<locals>.model_fn at 0x0000021148E3C620>) includes params argument, but params are not passed to Estimator.
WARNING:tensorflow:num_readers has been reduced to 0 to match input file shards.
WARNING:tensorflow:From F:\training\object_detection\builders\dataset_builder.py:80: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\training\object_detection\model_main.py", line 109, in <module>
    tf.app.run()
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "F:\training\object_detection\model_main.py", line 105, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\estimator\training.py", line 471, in train_and_evaluate
    return executor.run()
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\estimator\training.py", line 610, in run
    return self.run_local()
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\estimator\training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\estimator\estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1234, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1075, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1162, in _call_input_fn
    return input_fn(**kwargs)
  File "F:\training\object_detection\inputs.py", line 488, in _train_input_fn
    batch_size=params['batch_size'] if params else train_config.batch_size)
  File "F:\training\object_detection\builders\dataset_builder.py", line 134, in build
    config.input_path[:], input_reader_config)
  File "F:\training\object_detection\builders\dataset_builder.py", line 80, in read_dataset
    sloppy=config.shuffle))
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1190, in apply
    dataset = transformation_func(self)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\data\experimental\ops\interleave_ops.py", line 87, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\data\ops\readers.py", line 134, in __init__
    cycle_length, block_length)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2714, in __init__
    super(InterleaveDataset, self).__init__(input_dataset, map_func)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2677, in __init__
    experimental_nested_dataset_support=True)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1860, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\framework\function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\framework\function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\framework\function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\framework\function.py", line 864, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1794, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\data\ops\readers.py", line 200, in __init__
    filenames = ops.convert_to_tensor(filenames, dtype=dtypes.string)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\framework\ops.py", line 1050, in convert_to_tensor
    as_ref=False)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\framework\ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\framework\ops.py", line 983, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'`

### I think the problem is this
`WARNING:tensorflow:num_readers has been reduced to 0 to match input file shards.`

it's not getting any input shards.
 I am stuck on this from past 5 days, help me out!!

**Comment by BennuFire** [comment]
Are you running on Windows?

**Comment by atomsmasher81** [comment]
Yes window 10

**Comment by BennuFire** [comment]
@atomsmasher81 , check pipeline.config on ./tmp. Set paths to train and eval input readers with /

**Comment by atomsmasher81** [comment]
thanks a lot
